# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Student webcamp
email: student@webcamp.com.ua
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://student.webcamp.com.ua" # the base hostname & protocol for your site
twitter_username: student_webcamp
github_username: student-webcamp

# Build settings
markdown: kramdown
permalink: /:title

# collections
collections:
  tutorials:
    output: true
  webcamp:
    output: true

#variables
defaults:
  -
    scope:
      path: ""
      type: "posts" # a collection in your site, in plural form
    values:
      level: 1
      description: "Student Webcamp - ресурс для тех, кто хочет уметь"
      fbimg: "/img/icons/logo_student.png"